[project]
name = "python-ai-samples"
version = "0.1.0"
description = "Sample apps for building AI projects with Python and hosting them on Azure"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-inference>=1.0.0b9",
    "azure-identity>=1.24.0",
    "python-dotenv>=1.1.1",
]
